FROM ubuntu:26.04

# https://github.com/moby/buildkit/blob/master/frontend/dockerfile/docs/reference.md#run---mounttypecache
RUN rm -f /etc/apt/apt.conf.d/docker-clean; echo 'Binary::apt::APT::Keep-Downloaded-Packages "true";' > /etc/apt/apt.conf.d/keep-cache

RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,target=/var/lib/apt,sharing=locked \
    apt update && \
    DEBIAN_FRONTEND="noninteractive" apt-get -y install tzdata && \
    apt install -y --no-install-recommends nano ca-certificates python3 python3-pip python3-venv python3-flask wget curl gnupg2 gfortran libopenblas-dev liblapack-dev dos2unix && \
    mkdir -p /etc/apt/keyrings && \
    wget -qO- https://dl.google.com/linux/linux_signing_key.pub \
      | gpg --dearmor -o /etc/apt/keyrings/google-chrome.gpg && \
    echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/google-chrome.gpg] https://dl.google.com/linux/chrome/deb/ stable main" \
      > /etc/apt/sources.list.d/google-chrome.list && \
    apt update && \
    apt install -y google-chrome-stable && \
    apt -y upgrade && \
    apt autoremove -y

ENV VIRTUAL_ENV=/opt/venv
RUN python3 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

WORKDIR /

# https://docs.docker.com/build/guide/mounts/#add-a-cache-mount
RUN --mount=type=cache,target=/root/.cache/pip,sharing=locked pip3 install uv

ENV VIRTUAL_ENV=/.venv

# Prevent uv from using hardlinks across filesystems
ENV UV_LINK_MODE=copy

COPY pyproject.toml uv.lock /

# Sync dependencies only (Leverages Docker cache mount + file binds)
RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync --locked --no-dev

HEALTHCHECK --interval=10s --timeout=5s --start-period=15s \
   CMD curl --fail localhost:5000/health || exit 1

COPY init-embedding.py /

RUN HF_HOME=/root/.cache/huggingface \
    uv run /init-embedding.py

# after we download any Huggingface models, run it completely offline
ENV HF_HUB_OFFLINE=1
ENV TRANSFORMERS_OFFLINE=1

COPY ./flask/startup-dev.sh /
RUN dos2unix /startup-dev.sh && chmod +x /startup-dev.sh

ENV FLASK_APP=flaskapp

# add path to gunicorn
ENV PATH="${PATH}:/root/.local/bin/"

COPY ./flask/flaskapp/ /flaskapp
