services:
  trainclassifier:
    build:
      context: .
      dockerfile: Dockerfile_train_classifier.txt
      args:
        DOCKER_BUILDKIT: 1
    environment:
      TZ: America/Chicago
    volumes:
      - ./data/:/data/:ro
      - ./models/:/models:rw

  llm:
    build:
      context: .
      dockerfile: Dockerfile_llm.txt
      args:
        DOCKER_BUILDKIT: 1
    environment:
      TZ: America/Chicago
      OPENAI_BASE_URL: ${OPENAI_BASE_URL}
      OPENAI_API_BASE: ${OPENAI_API_BASE}
      API_BASE: ${API_BASE}
      LLM_MODEL: ${LLM_MODEL}
      CREW_VERBOSE_OUTPUT: ${CREW_VERBOSE_OUTPUT}
      SEARX_HOST: ${SEARX_HOST}
      SKILLS: ${SKILLS}
      RESUME: ${RESUME}
      DO_NOT_MATCH: ${DO_NOT_MATCH}
    volumes:
      - ./models/:/models:ro
      - ./results/:/results:rw
